name: ez80-for-rc-bbc-basic

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  ez80-for-rc-bbc-basic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: install ez80-clang
        run: |
          wget --progress=dot:giga https://github.com/dinoboards/ez80-clang/releases/download/v0.0.13-rc.81/ez80-clang-v0.0.13-rc.81.tar.gz
          tar -xzvf ez80-clang-v0.0.13-rc.81.tar.gz
          cd ez80-clang-v0.0.13-rc.81
          sudo ./install.sh

      - name: build
        run: |
          source /home/runner/.ez80-clang
          make

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: bbcbasic
          path: |
            bin/*.EXE

